name: Deploy to CentOS Server

on:
 push:
  branches:
   - master

jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Copy files to server
     uses: appleboy/scp-action@master
     with:
      host: ${{ secrets.TG_HOST }}
      username: ${{ secrets.TG_USER }}
      password: ${{ secrets.TG_PASS }}
      source: './'
      target: /www/nest-server/

   - name: SSH to server and restart application
     uses: appleboy/ssh-action@master
     with:
      host: ${{ secrets.TG_HOST }}
      username: ${{ secrets.TG_USER }}
      password: ${{ secrets.TG_PASS }}
      script: |
        cd /www/nest-server
        npx pnpm install
        npm run build
