name: Deploy to Tencent Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: release
        uses: actions/setup-node@v1
        with:
          node-version: 20.8.1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -  run: 
           npx pnpm install
           npm run semantic-release

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.TG_HOST }}
          username: ${{ secrets.TG_USER }}
          password: ${{ secrets.TG_PASS }}
          port: ${{ secrets.REMOTE_PORT }}
          source: './'
          target: /www/blog-server/

      - name: SSH to server and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TG_HOST }}
          username: ${{ secrets.TG_USER }}
          password: ${{ secrets.TG_PASS }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd /www/blog-server
            npx pnpm install
            npm run build
            npm run pm2 
